import type { AppActionId } from "@/actions/appActions";

export type ShortcutCategory = "navigation" | "edit" | "activity" | "task" | "planner" | "timetable" | "timer";
export type ShortcutMode = "single" | "sequence";

interface ShortcutDefinitionBase {
  sequence: string;
  mode: ShortcutMode;
  category: ShortcutCategory;
  action: string;
  note: string;
}

export interface ShortcutActionDefinition extends ShortcutDefinitionBase {
  actionId: AppActionId;
  displayOnly?: false;
}

export interface ShortcutDisplayDefinition extends ShortcutDefinitionBase {
  feature: string;
  displayOnly: true;
}

export type ShortcutDefinition = ShortcutActionDefinition | ShortcutDisplayDefinition;

export const SHORTCUT_DEFINITIONS: ShortcutDefinition[] = [
  {
    sequence: "Space",
    feature: "navigator.field.activate",
    mode: "single",
    category: "edit",
    action: "激活字段",
    note: "在行选择模式中激活当前字段或子选择；首页 Planner day 已选行且未进 pn 时直接切换该行勾选",
    displayOnly: true,
  },
  {
    sequence: "Enter",
    feature: "navigator.field.confirm",
    mode: "single",
    category: "edit",
    action: "确认当前字段",
    note: "确认当前字段动作；常用于提交当前编辑项",
    displayOnly: true,
  },
  {
    sequence: "Esc",
    feature: "navigator.mode.exit",
    mode: "single",
    category: "edit",
    action: "退出当前状态",
    note: "退出当前编辑/选择状态；输入框内会先退出输入焦点",
    displayOnly: true,
  },
  {
    sequence: "↑ / ↓",
    feature: "navigator.row.move",
    mode: "single",
    category: "edit",
    action: "行间移动",
    note: "在当前列表中移动行选择；激活子选择时按网格步进移动",
    displayOnly: true,
  },
  {
    sequence: "← / →",
    feature: "navigator.field.move",
    mode: "single",
    category: "edit",
    action: "字段切换",
    note: "在可编辑字段间切换；激活子选择时左右切换选项",
    displayOnly: true,
  },
  {
    sequence: "oo",
    actionId: "view.toggle.ontop",
    mode: "single",
    category: "navigation",
    action: "切换置顶模式",
    note: "时钟窗口置顶，仅桌面应用有效",
  },
  {
    sequence: "uu",
    actionId: "view.toggle.timer",
    mode: "single",
    category: "navigation",
    action: "切换区域显示",
    note: "番茄时钟（Timer）",
  },
  {
    sequence: "aa",
    actionId: "view.toggle.activity",
    mode: "single",
    category: "navigation",
    action: "切换区域显示",
    note: "活动清单（Activity）",
  },
  {
    sequence: "pp",
    actionId: "view.toggle.planner",
    mode: "single",
    category: "navigation",
    action: "切换区域显示",
    note: "任务计划（Planner）",
  },
  {
    sequence: "tt",
    actionId: "view.toggle.task",
    mode: "single",
    category: "navigation",
    action: "切换区域显示",
    note: "任务追踪（Task）",
  },
  {
    sequence: "mm",
    actionId: "view.toggle.timetable",
    mode: "single",
    category: "navigation",
    action: "切换区域显示",
    note: "时间表（Timetable）",
  },

  { sequence: "vh", actionId: "route.go.home", mode: "sequence", category: "navigation", action: "页面跳转", note: "首页（Home）" },
  { sequence: "vp", actionId: "route.go.help", mode: "sequence", category: "navigation", action: "页面跳转", note: "帮助（Help）" },
  { sequence: "vs", actionId: "route.go.search", mode: "sequence", category: "navigation", action: "页面跳转", note: "搜索（Search）" },
  {
    sequence: "vd",
    actionId: "route.go.dashboard",
    mode: "sequence",
    category: "navigation",
    action: "页面跳转",
    note: "仪表盘（Dashboard）",
  },
  { sequence: "ve", actionId: "route.go.settings", mode: "sequence", category: "navigation", action: "页面跳转", note: "设置（Setting）" },
  {
    sequence: "an",
    actionId: "activity.navigator.enter",
    mode: "sequence",
    category: "activity",
    action: "进入行选择模式",
    note: "在活动列表中可用 ↑/↓ 移动，数字选中，Enter/Esc 退出",
  },
  { sequence: "app", actionId: "activity.pickOrJump", mode: "sequence", category: "activity", action: "选择活动", note: "选中当前活动" },
  {
    sequence: "add",
    actionId: "activity.deleteOrRecover",
    mode: "sequence",
    category: "activity",
    action: "切换删除状态",
    note: "删除或恢复当前活动",
  },
  {
    sequence: "ach",
    actionId: "activity.toggleChild",
    mode: "sequence",
    category: "activity",
    action: "切换子级关系",
    note: "将当前活动设为或取消子级",
  },
  {
    sequence: "ato",
    actionId: "activity.addTodo",
    mode: "sequence",
    category: "activity",
    action: "加入 Todo",
    note: "从当前活动创建并关联 Todo；随后自动进入行导航并激活标题编辑",
  },
  {
    sequence: "asc",
    actionId: "activity.addSchedule",
    mode: "sequence",
    category: "activity",
    action: "加入 Schedule",
    note: "从当前活动创建并关联 Schedule；随后自动进入行导航并激活标题编辑",
  },
  {
    sequence: "aun",
    actionId: "activity.addUntaetigkeit",
    mode: "sequence",
    category: "activity",
    action: "加入 Untaetigkeit",
    note: "从当前活动创建并关联 Untaetigkeit；随后自动进入行导航并激活标题编辑",
  },
  {
    sequence: "aqu",
    actionId: "activity.toggleQuadrant",
    mode: "sequence",
    category: "activity",
    action: "切换象限",
    note: "修改当前活动的象限",
  },
  {
    sequence: "aka",
    actionId: "activity.addKanbanSection",
    mode: "sequence",
    category: "activity",
    action: "新增看板列",
    note: "在当前活动下新增一个看板列",
  },
  {
    sequence: "akd",
    actionId: "activity.removeKanbanSection",
    mode: "sequence",
    category: "activity",
    action: "删除最后看板列",
    note: "移除当前活动下最后一个看板列",
  },
  { sequence: "aet", actionId: "activity.editTitle", mode: "sequence", category: "activity", action: "编辑标题", note: "打开标题编辑" },
  { sequence: "aed", actionId: "activity.editDueDate", mode: "sequence", category: "activity", action: "编辑日期", note: "打开日期编辑" },
  { sequence: "aew", actionId: "activity.editPlace", mode: "sequence", category: "activity", action: "编辑地点", note: "打开地点编辑" },
  { sequence: "ael", actionId: "activity.editDuration", mode: "sequence", category: "activity", action: "编辑时长", note: "打开时长编辑" },
  {
    sequence: "aes",
    actionId: "activity.editScheduleTime",
    mode: "sequence",
    category: "activity",
    action: "编辑开始时间",
    note: "打开开始时间编辑",
  },
  {
    sequence: "aep",
    actionId: "activity.editPomoEstimate",
    mode: "sequence",
    category: "activity",
    action: "编辑番茄估算",
    note: "打开番茄估算编辑",
  },
  {
    sequence: "are",
    actionId: "activity.repeatActivity",
    mode: "sequence",
    category: "activity",
    action: "重复活动",
    note: "复制当前活动并保留在当前侧编辑",
  },
  { sequence: "tee", actionId: "task.openEditor", mode: "sequence", category: "task", action: "打开编辑区", note: "编辑当前任务" },
  { sequence: "tst", actionId: "task.toggleStar", mode: "sequence", category: "task", action: "切换星标", note: "标记或取消星标" },
  {
    sequence: "ttg",
    actionId: "task.openTagManager",
    mode: "sequence",
    category: "task",
    action: "打开标签管理",
    note: "编辑当前任务标签",
  },
  { sequence: "ten", actionId: "task.openEnergyDialog", mode: "sequence", category: "task", action: "打开能量面板", note: "编辑能量信息" },
  { sequence: "trw", actionId: "task.openRewardDialog", mode: "sequence", category: "task", action: "打开奖励面板", note: "编辑奖励信息" },
  {
    sequence: "tin",
    actionId: "task.openInterruptionDialog",
    mode: "sequence",
    category: "task",
    action: "打开打断面板",
    note: "编辑打断信息",
  },
  {
    sequence: "ttm",
    actionId: "task.openTemplateDialog",
    mode: "sequence",
    category: "task",
    action: "打开模板面板",
    note: "选择或应用模板",
  },
  { sequence: "tpr", actionId: "task.goPrev", mode: "sequence", category: "task", action: "切换到上一个任务", note: "定位上一个任务" },
  { sequence: "tnx", actionId: "task.goNext", mode: "sequence", category: "task", action: "切换到下一个任务", note: "定位下一个任务" },
  {
    sequence: "pn",
    actionId: "planner.navigator.enter",
    mode: "sequence",
    category: "planner",
    action: "进入 Planner 行选择模式",
    note: "随后可用 ↑/↓ 移动，数字选中，Enter/Esc 退出",
  },
  { sequence: "pgp", actionId: "planner.gotoPrev", mode: "sequence", category: "planner", action: "日期翻页", note: "上一周期" },
  { sequence: "pgn", actionId: "planner.gotoNext", mode: "sequence", category: "planner", action: "日期翻页", note: "下一周期" },
  { sequence: "ptn", actionId: "planner.gotoCurrent", mode: "sequence", category: "planner", action: "定位当前周期", note: "跳回当前周期" },
  {
    sequence: "ptd",
    actionId: "planner.gotoTodayDay",
    mode: "sequence",
    category: "planner",
    action: "定位今天并切 day 视图",
    note: "跳到今天并切换到 day",
  },
  { sequence: "pdd", actionId: "planner.gotoDay", mode: "sequence", category: "planner", action: "切换视图", note: "day" },
  { sequence: "pww", actionId: "planner.gotoWeek", mode: "sequence", category: "planner", action: "切换视图", note: "week" },
  { sequence: "pmm", actionId: "planner.gotoMonth", mode: "sequence", category: "planner", action: "切换视图", note: "month" },
  { sequence: "pyy", actionId: "planner.gotoYear", mode: "sequence", category: "planner", action: "切换视图", note: "year" },
  {
    sequence: "pto",
    actionId: "planner.addTodo",
    mode: "sequence",
    category: "planner",
    action: "新增 Todo",
    note: "在当前日期新增 Todo；随后自动进入 Planner 行导航并激活单元格编辑（day 视图）",
  },
  {
    sequence: "psc",
    actionId: "planner.addSchedule",
    mode: "sequence",
    category: "planner",
    action: "新增 Schedule",
    note: "在当前日期新增 Schedule（Untaetigkeit 归入 Schedule）；随后自动进入 Planner 行导航并激活单元格编辑（day 视图）",
  },
  { sequence: "pet", actionId: "planner.editTitle", mode: "sequence", category: "planner", action: "编辑标题", note: "打开标题编辑" },
  {
    sequence: "pes",
    actionId: "planner.editStart",
    mode: "sequence",
    category: "planner",
    action: "编辑开始时间",
    note: "打开开始时间编辑",
  },
  {
    sequence: "ped",
    actionId: "planner.editDone",
    mode: "sequence",
    category: "planner",
    action: "编辑完成状态",
    note: "打开完成状态编辑",
  },
  { sequence: "peu", actionId: "planner.editDuration", mode: "sequence", category: "planner", action: "编辑时长", note: "打开时长编辑" },
  { sequence: "pel", actionId: "planner.editLocation", mode: "sequence", category: "planner", action: "编辑地点", note: "打开地点编辑" },
  {
    sequence: "pre",
    actionId: "planner.repeatActivity",
    mode: "sequence",
    category: "planner",
    action: "重复活动（含关联项）",
    note: "会连同 Todo 或 Schedule 关系一起重复",
  },
  {
    sequence: "pic",
    actionId: "planner.exportIcs",
    mode: "sequence",
    category: "planner",
    action: "导出 ICS",
    note: "需要当前行可导出",
  },
  {
    sequence: "med",
    actionId: "timetable.toggleEditor",
    mode: "sequence",
    category: "timetable",
    action: "切换编辑状态",
    note: "开启或关闭编辑",
  },
  {
    sequence: "mex",
    actionId: "timetable.exitEditor",
    mode: "sequence",
    category: "timetable",
    action: "退出编辑",
    note: "结束当前编辑状态",
  },
  {
    sequence: "mtt",
    actionId: "timetable.toggleType",
    mode: "sequence",
    category: "timetable",
    action: "切换类型",
    note: "切换当前项类型",
  },
  {
    sequence: "uwu",
    actionId: "timer.startWork",
    mode: "sequence",
    category: "timer",
    action: "开始番茄工作",
    note: "遵循可执行条件",
  },
  {
    sequence: "ubr",
    actionId: "timer.startBreak",
    mode: "sequence",
    category: "timer",
    action: "开始休息",
    note: "遵循可执行条件",
  },
  {
    sequence: "ust",
    actionId: "timer.stop",
    mode: "sequence",
    category: "timer",
    action: "停止当前计时",
    note: "遵循可执行条件",
  },
];

export function buildShortcutActionMap(mode: ShortcutMode): Record<string, AppActionId> {
  const entries = SHORTCUT_DEFINITIONS.filter((item): item is ShortcutActionDefinition => item.mode === mode && !item.displayOnly).map(
    (item) => [item.sequence, item.actionId] as const,
  );
  return Object.fromEntries(entries);
}
