/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityButtons: typeof import('./components/ActivitySheet/ActivityButtons.vue')['default']
    ActivitySection: typeof import('./components/ActivitySheet/ActivitySection.vue')['default']
    ActivitySheet: typeof import('./components/ActivitySheet/ActivitySheet.vue')['default']
    AIChatDialog: typeof import('./components/AIChat/AIChatDialog.vue')['default']
    DayPlanner: typeof import('./components/DayPlanner/DayPlanner.vue')['default']
    DaySchedule: typeof import('./components/DayPlanner/DaySchedule.vue')['default']
    DayTodo: typeof import('./components/DayPlanner/DayTodo.vue')['default']
    EnergyInputDialog: typeof import('./components/TaskTracker/EnergyInputDialog.vue')['default']
    Icon: typeof import('./components/Common/Icon.vue')['default']
    InterruptionInputDialog: typeof import('./components/TaskTracker/InterruptionInputDialog.vue')['default']
    MessageDispatcher: typeof import('./components/AIChat/MessageDispatcher.vue')['default']
    MonthPlanner: typeof import('./components/MonthPlanner/MonthPlanner.vue')['default']
    NAvatar: typeof import('naive-ui')['NAvatar']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NDatePicker: typeof import('naive-ui')['NDatePicker']
    NIcon: typeof import('naive-ui')['NIcon']
    NInput: typeof import('naive-ui')['NInput']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutContent: typeof import('naive-ui')['NLayoutContent']
    NLayoutFooter: typeof import('naive-ui')['NLayoutFooter']
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NModal: typeof import('naive-ui')['NModal']
    NPopover: typeof import('naive-ui')['NPopover']
    NText: typeof import('naive-ui')['NText']
    PomodoroSequence: typeof import('./components/PomotentionTimer/PomodoroSequence.vue')['default']
    PomodoroTimer: typeof import('./components/PomotentionTimer/PomodoroTimer.vue')['default']
    PomotentionTimer: typeof import('./components/PomotentionTimer/PomotentionTimer.vue')['default']
    RewardInputDialog: typeof import('./components/TaskTracker/RewardInputDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SyncPanel: typeof import('./components/SyncPanel.vue')['default']
    TagManager: typeof import('./components/TagSystem/TagManager.vue')['default']
    TagRenderer: typeof import('./components/TagSystem/TagRenderer.vue')['default']
    TagSelector: typeof import('./components/TagSystem/TagSelector.vue')['default']
    TaskButtons: typeof import('./components/TaskTracker/TaskButtons.vue')['default']
    TaskRecord: typeof import('./components/TaskTracker/TaskRecord.vue')['default']
    TaskTracker: typeof import('./components/TaskTracker/TaskTracker.vue')['default']
    TemplateDialog: typeof import('./components/TaskTracker/TemplateDialog.vue')['default']
    TimeBlocks: typeof import('./components/TimeTable/TimeBlocks.vue')['default']
    TimeTable: typeof import('./components/TimeTable/TimeTable.vue')['default']
    TimeTableEditor: typeof import('./components/TimeTable/TimeTableEditor.vue')['default']
    UpdateManager: typeof import('./components/UpdateManager.vue')['default']
    WebdavInputDialog: typeof import('./components/WebdavInputDialog.vue')['default']
    WeekPlanner: typeof import('./components/WeekPlanner/WeekPlanner.vue')['default']
  }
}
